"""auto-vote

Revision ID: 46c7e2997a8c
Revises: bdda07b24b3a
Create Date: 2024-12-08 12:43:11.424421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46c7e2997a8c'
down_revision: Union[str, None] = 'bdda07b24b3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('votes', sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vote', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['Posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE' ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Posts', sa.Column('Shaina', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_posts_Shaina', 'Posts', 'users', ['Shaina'], ['email'])
    # ### end Alembic commands ###
